import os
import sys
import glob
import hashlib
import polars as pl

# Constants matching your pipeline specifications
FINAL_DATA_SIZE = 2_000_000  # 2 Million positions per wave (MUST be an EVEN number)
CLEAN_BINARY_DIR = "./clean_binary_shards"  # Input directory from exporter
PRODUCTION_DIR = "./clean_binary_production" # Final randomized output directory

def run_global_reservoir_shuffle():
    """
    Performs out-of-core global mixing across all cleaned Parquet waves.
    1. Globally deduplicates FENs keeping the highest search depth.
    2. Mirrors data on-the-fly via array-swapping to ensure 50/50 color balance.
    3. Uses hash-sorting to shuffle positions randomly while keeping twin blocks locked together.
    """
    os.makedirs(PRODUCTION_DIR, exist_ok=True)
    
    # 1. Discover all clean files generated by dataset_exporter.py
    input_pattern = os.path.join(CLEAN_BINARY_DIR, "clean_wave_*.parquet")
    cleaned_shards = sorted(glob.glob(input_pattern))
    
    if not cleaned_shards:
        print(f"[ERROR] No clean shards found in {CLEAN_BINARY_DIR}!")
        print("Please run dataset_exporter.py first to generate baseline clean data.")
        sys.exit(1)
        
    print(f"=== Commencing Global Deduplication & Mixer Across {len(cleaned_shards)} Shards ===")
    
    # 2. Lazily scan all input shards via Polars
    try:
        lazy_frames = [pl.scan_parquet(path) for path in cleaned_shards]
        combined_dataset = pl.concat(lazy_frames)
    except Exception as e:
        print(f"[ERROR] Failed to read shards: {e}")
        sys.exit(1)

    print(" -> Ingesting data and removing duplicate positions globally...")
    
    # 3. Global Deduplication Pipeline
    # We sort by 'depth' descending so the highest depth survives, then drop duplicate FENs
    df_unique = (
        combined_dataset
        .sort("depth", descending=True)
        .unique(subset=["fen"], keep="first")
        .collect(streaming=True)
    )
    
    print(f" -> Deduplication complete. Unique positions found: {len(df_unique):,}")
    print(" -> Generating mirrored perspectives and applying grouped shuffle...")

    # 4. On-The-Fly Mirroring & Hashing via Polars Vectorization (Ultra Fast!)
    # Create the mirrored counterparts using your exact array-swapping and score inversion logic
    df_original = df_unique.select([
        pl.col("white_indices"),
        pl.col("black_indices"),
        pl.col("is_black_turn").cast(pl.Float64),
        pl.col("target").cast(pl.Float64),
        # Hash the original FEN so twins share an identical sorting identifier
        pl.col("fen").map_elements(
            lambda f: int(hashlib.md5(f.encode('utf-8')).hexdigest(), 16) % (10**10),
            return_dtype=pl.Int64
        ).alias("position_hash")
    ])

    df_mirrored = df_unique.select([
        pl.col("black_indices").alias("white_indices"),  # Swap arrays
        pl.col("white_indices").alias("black_indices"),  # Swap arrays
        (1.0 - pl.col("is_black_turn").cast(pl.Float64)).alias("is_black_turn"), # Invert turn
        (-pl.col("target").cast(pl.Float64)).alias("target"),  # Invert evaluation target
        pl.col("fen").map_elements(
            lambda f: int(hashlib.md5(f.encode('utf-8')).hexdigest(), 16) % (10**10),
            return_dtype=pl.Int64
        ).alias("position_hash")  # Identical hash links twins together
    ])

    # Interleave original and mirrored datasets back-to-back
    df_doubled = pl.concat([df_original, df_mirrored])
    
    # 5. Grouped Shuffle
    # Sorting by the random position_hash shuffles openings while keeping twins adjacent
    df_shuffled = df_doubled.sort("position_hash")
    
    total_rows = len(df_shuffled)
    print(f" -> Total perfectly balanced training rows compiled: {total_rows:,}")
    print(" -> Slicing data into final production shards...")

    # 6. Slice and export into 2 Million row production waves
    production_wave_counter = 1
    for j in range(0, total_rows, FINAL_DATA_SIZE):
        production_shard = df_shuffled.slice(j, FINAL_DATA_SIZE)
        
        # Avoid creating an incredibly tiny trailing file if it doesn't meet size requirements
        if len(production_shard) < FINAL_DATA_SIZE and production_wave_counter > 1:
            print(f" -> Appending {len(production_shard):,} trailing positions to the final shard.")
            break
            
        output_path = os.path.join(PRODUCTION_DIR, f"production_wave_{production_wave_counter}.parquet")
        
        # Save clean shard (dropping the hash column so your network template doesn't break)
        production_shard.drop("position_hash").write_parquet(output_path, compression="snappy")
        
        print(f"[PRODUCTION EXPORT {production_wave_counter}] Written {len(production_shard):,} rows.")
        production_wave_counter += 1

    print(f"\n[SUCCESS] Global Shuffling and Deduplication Complete!")
    print(f"Total Unique Production Waves Compiled: {production_wave_counter - 1}")

if __name__ == "__main__":
    run_global_reservoir_shuffle()
