import os
import sys
import glob
import polars as pl

# Constants matching your pipeline specifications
FINAL_DATA_SIZE = 2_000_000  # 2 Million positions per wave (MUST be an EVEN number)
CLEAN_BINARY_DIR = "./clean_binary_shards"  # Input directory from exporter
PRODUCTION_DIR = "./clean_binary_production" # Final randomized output directory

def run_global_reservoir_shuffle():
    """
    Performs out-of-core global mixing across all cleaned Parquet waves.
    1. Globally deduplicates FENs keeping the highest search depth.
    2. Leverages pre-existing position_hash from exporter for ultra-fast twin-locked shuffling.
    """
    os.makedirs(PRODUCTION_DIR, exist_ok=True)
         
    # 1. Discover all clean files generated by dataset_exporter.py
    input_pattern = os.path.join(CLEAN_BINARY_DIR, "clean_wave_*.parquet")
    cleaned_shards = sorted(glob.glob(input_pattern))
         
    if not cleaned_shards:
        print(f"[ERROR] No clean shards found in {CLEAN_BINARY_DIR}!")
        print("Please run dataset_exporter.py first to generate baseline clean data.")
        sys.exit(1)
             
    print(f"=== Commencing Global Deduplication & Mixer Across {len(cleaned_shards)} Shards ===")
         
    # 2. Lazily scan all input shards via Polars
    try:
        lazy_frames = [pl.scan_parquet(path) for path in cleaned_shards]
        combined_dataset = pl.concat(lazy_frames)
    except Exception as e:
        print(f"[ERROR] Failed to read shards: {e}")
        sys.exit(1)

    print(" -> Ingesting data and removing duplicate positions globally...")
         
    # 3. Global Deduplication Pipeline
    # Sort by 'depth' descending so highest depth survives. 
    # Because twins (Orig/Mirror) share the same FEN/Hash, we group by hash or fen.
    df_shuffled = (
        combined_dataset
        .sort("depth", descending=True)
        # Keeps both Perspective A and B for the highest-depth version of this position
        .unique(subset=["position_hash", "is_black_turn"], keep="first")
        # Global Grouped Shuffle: Sort by the pre-computed hash natively in Polars
        .sort("position_hash")
        .collect(streaming=True)
    )
         
    total_rows = len(df_shuffled)
    print(f" -> Deduplication complete. Balanced training rows compiled: {total_rows:,}")
    print(" -> Slicing data into final production shards...")
     
    # 4. Slice and export into 2 Million row production waves
    production_wave_counter = 1
    for j in range(0, total_rows, FINAL_DATA_SIZE):
        production_shard = df_shuffled.slice(j, FINAL_DATA_SIZE)
                 
        # Avoid creating an incredibly tiny trailing file if it doesn't meet size requirements
        if len(production_shard) < FINAL_DATA_SIZE and production_wave_counter > 1:
            print(f" -> Appending {len(production_shard):,} trailing positions to the final shard.")
            break
                     
        output_path = os.path.join(PRODUCTION_DIR, f"production_wave_{production_wave_counter}.parquet")
                 
        # Save clean shard (dropping metadata columns so your network template doesn't break)
        # Note: Keeps 'depth' and 'fen' dropped if they exist in the incoming shards
        columns_to_drop = [col for col in ["position_hash", "fen", "depth"] if col in production_shard.columns]
        
        production_shard.drop(columns_to_drop).write_parquet(output_path, compression="snappy")
                 
        print(f"[PRODUCTION EXPORT {production_wave_counter}] Written {len(production_shard):,} rows.")
        # Ensure our slicing increments perfectly by actual rows written
        production_wave_counter += 1

    print(f"\n[SUCCESS] Global Shuffling and Deduplication Complete!")
    print(f"Total Unique Production Waves Compiled: {production_wave_counter - 1}")

if __name__ == "__main__":
    run_global_reservoir_shuffle()
