# global_mixer.py
import os
import sys
import glob
import numpy as np
import pandas as pd

# Constants matching your pipeline specifications
FINAL_DATA_SIZE = 2_000_000  # 2 Million perfectly randomized positions per wave
CLEAN_BINARY_DIR = "./clean_binary_shards"  # Input directory from exporter
PRODUCTION_DIR = "./clean_binary_production" # Final randomized output directory

def run_global_reservoir_shuffle():
    """
    Performs out-of-core global mixing across all cleaned Parquet waves.
    Interleaves rows from multiple shards to permanently smash block data grouping bias.
    """
    os.makedirs(PRODUCTION_DIR, exist_ok=True)
    
    # 1. Discover all clean files generated by dataset_exporter.py
    input_pattern = os.path.join(CLEAN_BINARY_DIR, "clean_wave_*.parquet")
    cleaned_shards = sorted(glob.glob(input_pattern))
    
    if not cleaned_shards:
        print(f"[ERROR] No clean shards found in {CLEAN_BINARY_DIR}!")
        print("Please run dataset_exporter.py first to generate baseline clean data.")
        sys.exit(1)
        
    print(f"=== Commencing Global Reservoir Mix Across {len(cleaned_shards)} Shards ===")
    
    # 2. Open file iterators for all shards simultaneously to create a reservoir pool
    shard_readers = []
    for path in cleaned_shards:
        try:
            # We load the entire clean shard into a row generator
            df = pd.read_parquet(path)
            # Store as an iterator of rows to stream sequentially
            shard_readers.append(df.itertuples(index=False, name='ChessPosition'))
            print(f" -> Hooked streaming reader to: {os.path.basename(path)}")
        except Exception as e:
            print(f"[WARNING] Skipping corrupted shard {path}: {e}")

    production_wave_counter = 1
    global_reservoir = []
    
    # Define how many rows we pull from each file per round (e.g., 10,000 rows from each of the 20 shards)
    pull_chunk_size = 10000
    
    active_streams = True
    while active_streams:
        active_streams = False
        round_pool = []
        
        # 3. Interleave: Grab a balanced block of positions from every single file stream
        for reader in shard_readers:
            pulled_count = 0
            while pulled_count < pull_chunk_size:
                try:
                    row = next(reader)
                    # Convert row to dictionary to match your original Parquet schema
                    round_pool.append({
                        'white_indices': list(row.white_indices),
                        'black_indices': list(row.black_indices),
                        'is_black_turn': float(row.is_black_turn),
                        'target': float(row.target)
                    })
                    pulled_count += 1
                    active_streams = True
                except StopIteration:
                    break # This specific shard file stream has run completely dry
                    
        if not round_pool and not global_reservoir:
            break
            
        # Add the fresh interleaved rows into our main shuffling reservoir
        global_reservoir.extend(round_pool)
        
        # 4. Global Shuffle: Randomize the combined multi-shard soup completely in memory
        np.random.shuffle(global_reservoir)
        
        # 5. Export: Once our reservoir hits our 2 Million target boundary, write a production wave
        while len(global_reservoir) >= FINAL_DATA_SIZE:
            production_records = global_reservoir[:FINAL_DATA_SIZE]
            global_reservoir = global_reservoir[FINAL_DATA_SIZE:]
            
            output_path = os.path.join(PRODUCTION_DIR, f"production_wave_{production_wave_counter}.parquet")
            
            # Pack and save with Snappy compression
            df_out = pd.DataFrame(production_records)
            df_out.to_parquet(output_path, compression="snappy", index=False)
            
            print(f"\n[PRODUCTION EXPORT {production_wave_counter}] Written {FINAL_DATA_SIZE} perfectly mixed positions.")
            print(f" -> Output Path: {output_path}")
            production_wave_counter += 1
            
    # Flush any remaining stragglers left over at the absolute end of the pool
    if global_reservoir:
        output_path = os.path.join(PRODUCTION_DIR, f"production_wave_{production_wave_counter}.parquet")
        df_out = pd.DataFrame(global_reservoir)
        df_out.to_parquet(output_path, compression="snappy", index=False)
        print(f"\n[FINAL PRODUCTION EXPORT {production_wave_counter}] Written {len(global_reservoir)} trailing positions.")

    print(f"\n[SUCCESS] Global Shuffling Complete! Total Production Waves Compiled: {production_wave_counter}")
    print(f"You can now configure train_pipeline.py to point directly to: {PRODUCTION_DIR}")

if __name__ == "__main__":
    run_global_reservoir_shuffle()
